### ISSUE TITLE
회의실 예약등록 및 수정 시 time테이블에 반영

### ISSUE THREAD

**Issue by Dev-lemongrab** [4team-final/server#80]
## 💡 Issue
회의실 예약등록 및 수정 시 time테이블에 반영

소켓 disconnect 됬을때 타임테이블에 insert된것을 다시 전으로 되돌리는 기능

## 📝 todo
- [x] 등록
- [x] 수정
- [x]  disconnect 됬을때 타임테이블에 insert된것을 다시 전으로 되돌리는 기능

**Comment by jaebin1234** [comment]
이거 예약 등록 자체가 회의실+차량 선택/날짜선택 그 이후에 시간선택이기 때문에 수정하지 않아도 될것같습니다!!!

**Comment by jaebin1234** [comment]
오히려 웹소켓 disconnect 됬을때 타임테이블에 insert된것을 다시 전으로 되돌리는 기능이 필요합니다~
